defaults:
  - _self_
  - embeddings/transform:
    - affine_shuffle_pad

name: cifar10_embeddings
embeddings:
  train_path: ./src/data/embeddings/cifar10_emb_simsiam_train_dataset_noised.pt
  train_path2: ./src/data/embeddings/cifar10_emb_simsiam_train_dataset_noised_2.pt
  test_path: ./src/data/embeddings/cifar10_emb_simsiam_test_dataset.pt
  class_number: 10
hparams:
  train_epochs_reference_classifier: 50
  train_epochs_mapper: 50
#    train_mb_size: 64
#    eval_mb_size: 64
  lr_reference_classifier: 0.00001
#    gamma: floats
  lr_mapper: 0.00001
subsets: [10, 50, 100, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 10000, 50000]