defaults:
  - _self_
  - embeddings/transform:
    - affine

name: svhn_embeddings
embeddings:
  train_path: ./src/data/embeddings/svhn_emb_simsiam_train_dataset_noised.pt
  test_path: ./src/data/embeddings/svhn_emb_simsiam_test_dataset.pt
  class_number: 10
hparams:
  train_epochs_reference_classifier: 100
  train_epochs_mapper: 50
#    train_mb_size: 64
#    eval_mb_size: 64
  lr_reference_classifier: 0.0001
  #    gamma: float
  lr_mapper: 0.01
subsets: [10, 50, 100, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 10000, 50000]