defaults:
 - _self_
 - benchmark:
   - cifar10_embeddings

#  model:
#    load_path: pytorch/vision:v0.13.1
#    output_dim: 512

wandb:
  enable: False
  entity: stapaw
  project: encoder-defense
  tags: null
  name: null

normalize: False
output_dir: null
save_model: false
seed: 0
device: cuda
device_id: 1